### ISSUE TITLE
mz_costing returns a rectangle

### ISSUE THREAD

**Issue by duleise** [tarakc02/rmapzen#10] opened 2017-05-16 09:42 UTC
`mz_costing` is great.
In some cases it is more useful than similar functions which return point-to-point distance.

I was trying to plot areas within walking distance to closest subway stations. Some of the results from `mz_costing` didn't look right. See my codes below. `Gamla stan` and `Rådhuset` are two stations in Stockholm.
For `Gamla stan`, the returned area is a pretty regular rectangle, which is not what I would expect.
On the other hand, area for `Rådhuset` looks more real.
I also tried different arguments,
`mz_costing_options$pedestrian$walking_speed`
`mz_costing_options$pedestrian$alley_factor`
`mz_costing_options$pedestrian$walkway_factor`
The results looked similar, if not the same.
Any suggestions on what's wrong? or I am totally lost somewhere?
Thank you.

```
isos <- mz_isochrone(
  # Gamla stan
  mz_location(lat = 59.32340,
              lon = 18.06716),
  
  # Rådhuset
  # mz_location(lat = 59.32986,
  #             lon = 18.04510),
  costing_model = mz_costing$pedestrian(),
  contours = mz_contours(c(15))
)

data <- as_sp(isos)
data$color <- "forestgreen"
data$opacity <- c(.3)

m <- leaflet(data) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(fillColor = ~color, weight = 0, fillOpacity = ~opacity)
m
```

**Comment by tarakc02** [comment] 2017-05-16 19:09
Hmmn, I got the same outputs as you did. 

As far as I know there are two possible reasons why you'd end up with something unexpected here. The first is that the `rmapzen` package is not generating the correct http request based on your specifications. I took a look at the URL that the package built for your request, and couldn't find anything obviously wrong with it. The second possibility is that this result is what we are getting back from Mapzen. You can test this by using Mapzen's mobility explorer:

https://mapzen.com/mobility/explorer

When I tried the same request there, I also got a rectangular shape. And when I tried other addresses (couldn't find Rådhuset through their tool) the result looked, as you say, "more real." For what it's worth, when I do a similar request (15 minute walking contour) for UC Berkeley, I also get a rectangle both in `rmapzen` and in the Mobility Explorer. 

Which is all to say that, for that particular issue, it seems like the problem is what's coming from Mapzen, and not anything that's happening in the `rmapzen` package. So we need to submit an issue to: https://github.com/valhalla/valhalla. I'll see if there are any existing similar issues over there, if not I'll submit a new one.

I haven't had a chance to look at the different arguments problem yet, but before the end of the day I'll  take a look at the costing options and compare the URL generated by `rmapzen` to what should be expected based on the documentation.

**Comment by tarakc02** [comment] 2017-05-16 19:33
Regarding the rectangle isochrone contour issue, I've submitted an issue at:
valhalla/valhalla#721

**Comment by tarakc02** [comment] 2017-05-16 19:39
Update: looks like the fix for this has already been implemented, and will be rolling out to production sometime soon: https://github.com/valhalla/valhalla/issues/721#issuecomment-301891850

That means that you shouldn't have to do anything differently on your Gamla Stan example, and once the upstream fix is in production you'll see the correct results automatically.

I won't have a chance to look at the additional arguments until later this afternoon, but will respond here.

**Comment by tarakc02** [comment] 2017-05-17 22:01
@duleise: The issue that was causing the rectangle pedestrian results has been resolved (details at https://github.com/valhalla/valhalla/issues/721), and I've tested the Gamla stan example you provided and got reasonable (non-rectangle) results. Let me know if you still are having problems.

Regarding the problem with the additional options (such as mz_costing_options$pedestrian$walking_speed()`), can you provide a specific example of a search with and without some optional arguments where you expect different results but don't see them? It looks like the URLs for the requests are being constructed correctly (in accordance with Mapzen's documentation), and the couple of examples I tried did give me different results that seemed to make sense. For example, I tried:

```
isos <- mz_isochrone(
    mz_location(lat = 59.32340, lon = 18.06716),
    costing_model = mz_costing$pedestrian(),
    contours = mz_contours(15)
)
```

and plotted the results in leaflet. Then I did:

```
isos2 <- mz_isochrone(
    mz_location(lat = 59.32340, lon = 18.06716),
    costing_model = mz_costing$pedestrian(
        mz_costing_options$pedestrian$walking_speed(15)
    ),
    contours = mz_contours(15)
)
```
and plotted those results, and the latter showed a much larger area, as expected. The walking_speed is measured in km/hr and the default value is 5.1 (more info at `?mz_costing_options` and https://mapzen.com/documentation/mobility/turn-by-turn/api-reference/#costing-models)

**Comment by duleise** [comment] 2017-05-18 13:00
That's prompt and efficient.
I have checked and manually compared it with googlemaps routing tools. It seems alright to me.
Also, the unfunctional costing_options seems to be related to this rectangle issues. Now it all works.
Thank you very much.

**Comment by duleise** [comment] 2017-08-18 08:29
hi again. I am afraid I have to revisit this thread.
The example I showed in my initial post (`Gamla stan`) still works fine.
But I met another similar one today. See below. It looks like it comes from `mz_costing$auto()`
Any suggestion? Thank you.
  
  ```
isos <- mz_isochrone(
    # Gothenburg
    mz_location(lat = 57.73563,
                lon = 12.01429),

    costing_model = mz_costing$auto(),
    contours = mz_contours(c(60))
  )
  
  data <- as_sp(isos)
  data$color <- "forestgreen"
  data$opacity <- c(.3)
  
  m <- leaflet(data) %>%
    addProviderTiles("CartoDB.Positron") %>%
    addPolygons(fillColor = ~color, weight = 0, fillOpacity = ~opacity)
  m
```

**Comment by tarakc02** [comment] 2017-08-19 00:36
I am seeing the same issue as you when I run your code (thanks again for providing the code to reproduce the issue).  I went to https://mapzen.com/mobility/explorer and found the same problem, which leads me to believe that, as before, this issue is happening on the Mapzen side. I'm notifying them about the problem at valhalla/valhalla#721 (that was the original issue I opened in response to your original report) and will update this issue if/when there are updates.

**Comment by tarakc02** [comment] 2017-08-19 00:54
Woops, one more thought: by playing around with the mobility explorer, I found that if I moved the location from where you're calculating isochrones a little bit, everything worked fine. The exact location that you've used appears, on the map, to be a little ways away from the nearest road. So one solution might be to nudge your location a little bit. This worked for me:

```
isos <- mz_isochrone(
    mz_location(lat = 57.73563,
                lon = 12.0165),
    
    costing_model = mz_costing$auto(),
    contours = mz_contours(c(60))
)

data <- as_sp(isos)
data$color <- "forestgreen"
data$opacity <- c(.3)

m <- leaflet(data) %>%
    addProviderTiles("CartoDB.Positron") %>%
    addPolygons(fillColor = ~color, weight = 0, fillOpacity = ~opacity) 
m
```

**Comment by duleise** [comment] 2017-08-21 10:22
Thank you for your prompt replies. I tried your "nudge" solution and it works fine. Interestingly, the coordinates I used, which returned a rectangle, was from `mz_geocode`.
I guess the odd is very low. But when I do a batch isochrones calculating, it will be a pain to check and nudge this manually.
Let's hope Mapzen could trace it and have it fixed.
Thank you again.

```
> mz_geocode("Gothenburg")
# A tibble: 1 x 4
     geocode_address geocode_longitude geocode_latitude geocode_confidence
*              <chr>             <dbl>            <dbl>              <dbl>
1 Gothenburg, Sweden          12.01429         57.73563                  1

```

**Comment by tarakc02** [comment] 2017-08-21 18:50
Thanks,
Since it seems like there's nothing else I can do on the `rmapzen` side of things, I'm going to go ahead and re-close this issue. There is additional information from Mapzen, see the final comment here: valhalla/valhalla#721. 

But as you say, there may be problems any time we geocode a location that is not a single point (like Gothenberg, which is a polygon), in that the returned geocode will be the centroid or something like that, and it may or may not be adjacent to a road. It would be nice if the Isochrone service could make some adjustment to start at the nearest road. I guess another workaround is to use a more specific landmark to ensure that you'll get a point that is car-accessible. For instance, I tried your code but used:

```
mz_geocode("Gothenberg Centralstation")
```

And that gave the correct results. This may not always be possible . . ..

**Closed as completed by tarakc02** 2017-08-21 18:50 UTC
